---
title: CGI Results
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
    permalink: "/:collection/:title"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: services
  values:
    Image: ''
    Short Description: ''
    layout: page
email: your-email@example.com
description: CGi is a full-service association and events management company. We have
  a uniquely talented team and proven results in association growth and revenue diversification.
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jmotes
markdown: kramdown
plugins:
- jekyll-feed
- bootstrap
